apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockoon-k8s-hands-on
  labels:
    app: mockoon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockoon
  template:
    metadata:
      labels:
        app: mockoon
    spec:
      containers:
      - name: mockoon
        image: mockoon
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: mockoon-k8s-hands-on
  labels:
    app: mockoon
spec:
  type: NodePort
  selector:
    app: mockoon
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
